
Install web applications
version 0.1 
2018-07-01
The paths in this readme assume the organization of web directories
convenient for xampp.  The web directory for dictionary 'X' is, relative
to the directory of this websanlexicon directory, ../X/web

 
* inventory
Directories and files in web application subdirectories, specifically for 'gra'
** web directory files
graheader.xml
index.php
readme.txt

** images
images/cologne_univ_seal.gif
images/encoding.gif
** js
js/jquery.cookie.js
js/jquery.min.js
** mobile1
mobile1/index.php
mobile1/main.css
mobile1/main_mobile.js
mobile1/monier_serveimg.css
** sqlite
sqlite/def.sql
sqlite/gra.sqlite
sqlite/input.txt
sqlite/make_input.php
sqlite/redo.sh
** utilities
transcoder.php
** utilities/transcoder
utilities/transcoder/as_roman.xml
utilities/transcoder/deva_slp1.xml
utilities/transcoder/hk_slp1.xml
utilities/transcoder/itrans_slp1.xml
utilities/transcoder/roman_slp1.xml
utilities/transcoder/slp1_as.xml
utilities/transcoder/slp1_deva.xml
utilities/transcoder/slp1_hk.xml
utilities/transcoder/slp1_itrans.xml
utilities/transcoder/slp1_roman.xml
utilities/transcoder/slp1_romanpms.xml
utilities/transcoder/slp1_wx.xml
utilities/transcoder/wx_slp1.xml
** webtc
webtc/basicadjust.php
webtc/dal.php
webtc/dbgprint.php
webtc/dictcode.php
webtc/dictinfo.php
webtc/disp.php
webtc/download.html
webtc/getword.php
webtc/getwordviewmodel.php
webtc/help.html
webtc/indexcaller.php
webtc/main.css
webtc/main_webtc.js
webtc/parm.php
webtc/pdffiles.txt
webtc/serveimg.css
webtc/servepdf.php
webtc/translithelp.html
** webtc1
webtc1/disphier.php
webtc1/index.php
webtc1/keyboard.css
webtc1/keyboard.js
webtc1/keyboard.png
webtc1/listhier.php
webtc1/listhiermodel.php
webtc1/listhierview.php
webtc1/listparm.php
webtc1/main.css
webtc1/main.js
webtc1/preferences.htm
webtc1/transcoderfield_VKI.js
** webtc1/help
webtc1/help/accents.html
webtc1/help/ack.html
webtc1/help/definition.html
webtc1/help/help.css
webtc1/help/help.html
webtc1/help/help.js
webtc1/help/helpmain.html
** webtc1/help/images
webtc1/help/images/input.html
webtc1/help/images/keyboard.html
webtc1/help/images/links.html
webtc1/help/images/list.html
webtc1/help/images/phonetic.html
webtc1/help/images/preferences.html
webtc1/help/images/system.html
** webtc1/transcoderjs
webtc1/transcoderjs/transcoder3.js
webtc1/transcoderjs/transcoderJson.js
** webtc2
webtc2/help.html
webtc2/index.php
webtc2/init_query.php
webtc2/init_query.sh
webtc2/main.css
webtc2/main.js
webtc2/query.php
webtc2/query_dump.txt
webtc2/query_gather.php
webtc2/query_multi.php
webtc2/querylistview.php
webtc2/querymodel.php
webtc2/queryparm.php

** not included
mobile1/old:
utilities/old:
utilities/transcoder/old:
utilities/transcoder/pms:
webtc/old:
webtc1/old:
webtc1/old1:
webtc2/old:
webtc2/old1:
* INSTALLING:
** directories which are same for all dictionaries
 images, 
 js, 
 utilities, utilities/transcoder,
 webtc1/help webtc1/help/images, webtc1/transcoderjs
** sqlite directory
   def.sql, make_input.php, and redo.sh are used to generate
   gra.sqlite from gra.xml.
   input.txt is an intermediate file.
   Only gra.sqlite is used by displays.
   For some other dictionaries, xab.sqlite and xauth.sqlite are used
   by displays.
 The data constructors in webtc need to know where the sqlite database
 files reside, and their name and table names. e.g. gra.sqlite has table
 named gra.
 Other tables could be put into gra.sqlite, but this is not done now.
 The current convention is that if X.sqlite is the filename, then the
 table name is X  (e.g. whitmwtab.sqlite has table name whitmwtab.)
* webtc2/query_dump.txt
* next
* ----------------------------------------------------------
* backup an inventory file for previous code
# in websanlexicon:
These backups are done prior to the installation of version 00.
python backup.py inventories/gra_00.txt ../gra/web  webbackup/gra/00
python backup.py inventories/bur_00.txt ../bur/web  webbackup/bur/00
python backup.py inventories/cae_00.txt ../cae/web  webbackup/cae/00
python backup.py inventories/stc_00.txt ../stc/web  webbackup/stc/00
python backup.py inventories/pwg_00.txt ../pwg/web  webbackup/pwg/00
python backup.py inventories/mw_00.txt ../mw/web  webbackup/mw/00
python backup.py inventories/skd_00.txt ../skd/web  webbackup/skd/00
python backup.py inventories/ae_00.txt ../ae/web  webbackup/ae/00
python backup.py inventories/pw_00.txt ../pw/web  webbackup/pw/00
python backup.py inventories/ap90_00.txt ../ap90/web  webbackup/ap90/00
python backup.py inventories/ap_00.txt ../ap/web  webbackup/ap/00
python backup.py inventories/pd_00.txt ../pd/web  webbackup/pd/00
python backup.py inventories/bhs_00.txt ../bhs/web  webbackup/bhs/00
python backup.py inventories/wil_00.txt ../wil/web  webbackup/wil/0
python backup.py inventories/yat_00.txt ../yat/web  webbackup/yat/00
python backup.py inventories/shs_00.txt ../shs/web  webbackup/shs/00
python backup.py inventories/gst_00.txt ../gst/web  webbackup/gst/00
python backup.py inventories/vcp_00.txt ../vcp/web  webbackup/vcp/00
python backup.py inventories/ben_00.txt ../ben/web  webbackup/ben/00
python backup.py inventories/bop_00.txt ../bop/web  webbackup/bop/00
python backup.py inventories/bor_00.txt ../bor/web  webbackup/bor/00
python backup.py inventories/ccs_00.txt ../ccs/web  webbackup/ccs/00
python backup.py inventories/md_00.txt ../md/web  webbackup/md/00
python backup.py inventories/mwe_00.txt ../mwe/web  webbackup/mwe/00
python backup.py inventories/mw72_00.txt ../mw72/web  webbackup/mw72/00
python backup.py inventories/ieg_00.txt ../ieg/web  webbackup/ieg/00
python backup.py inventories/inm_00.txt ../inm/web  webbackup/inm/00
python backup.py inventories/krm_00.txt ../krm/web  webbackup/krm/00
python backup.py inventories/mci_00.txt ../mci/web  webbackup/mci/00
python backup.py inventories/pe_00.txt ../pe/web  webbackup/pe/00
python backup.py inventories/pgn_00.txt ../pgn/web  webbackup/pgn/00
python backup.py inventories/pui_00.txt ../pui/web  webbackup/pui/00
python backup.py inventories/sch_00.txt ../sch/web  webbackup/sch/00
python backup.py inventories/snp_00.txt ../snp/web  webbackup/snp/00
python backup.py inventories/vei_00.txt ../vei/web  webbackup/vei/00
python backup.py inventories/acc_00.txt ../acc/web  webbackup/acc/00

* ----------------------------------------------------------
* v00 -- initial 'general' version of web
  starts as a copy of webbackup/gra/00
* install datafiles to move
pdfpages # directory
fonts    # directory
sqlite/gra.sqlite 
sqlite/graab.sqlite
sqlite/gramwauth.sqlite
webtc2/query_dump.txt
webtc/pdffiles.txt

* regenerate gra in place  (modifies 'web' directly)
#in v00
python generate.py gra inventory.txt  makotemplates ../../gra/web
* v00 generate and install: gra
cd v00
python generate.py gra inventory.txt  makotemplates grav00
cp -Tr grav00 ../../gra/webv00

#python generate.py gra temp_inventory.txt  temp_templates tempdir

# python install.py <dictcode> <dirin> <diroutparent>
 python install.py gra ../../gra/webv00 ../../gra


* v00 generate and install: bur
cd v00
python generate.py bur inventory.txt  makotemplates ../../bur/webv00
# cp -Tr grav00 ../../gra/webv00

# python install.py <dictcode> <dirin> <diroutparent>
 python install.py bur ../../bur/webv00 ../../bur

* regenerate bur in place  (modifies 'web' directly)
#in v00
python generate.py bur inventory.txt  makotemplates ../../bur/web
* TODO 'outopt' in webtc2
  This is vestigial.  Needs to be removed in several places:
    main.js, queryParm.php, index.php, elsewhere?
* TODO modifyDeva in main.js
  Is this the right way to insure Siddhanta font for devanagari output?
* DONE accent
  This is a display option. Implement in BasicAdjust? 
  Currently a parameter in query_multi.php
* v00 generate and install: cae
cd v00
python generate.py cae inventory.txt  makotemplates ../../cae/webv00

#python generate.py cae temp_inventory.txt  temp_templates tempdir

# python install.py <dictcode> <dirin> <diroutparent>
 python install.py cae ../../cae/webv00 ../../cae
* regenerate cae in place  (modifies 'web' directly)
#in v00
python generate.py cae inventory.txt  makotemplates ../../cae/web
* DONE Use siddhanta font
* v00 generate  stc 07-08-2018
This is peculiar, because there are Frenchified versions of some displays:
webtc/download_fr.html , help_fr.html , indexcaller_fr.php
These are processed by generate.py as additional inventory files.

cd v00
python generate.py stc inventory.txt  makotemplates ../../stc/webv00

* install stc 07-08-2018
 python install.py stc ../../stc/webv00 ../../stc
* regenerate stc/web in place  
#in v00
python generate.py stc inventory.txt  makotemplates ../../stc/web
* ----------pwg---------------------
* NOTES on PWG conversion
** pwgauth  
   This is first dictionary conversion with links resolving ls (works/authors)
   sqlite file named pwgbib  (why not pwgauth?) -- basicadjust.php
      structure: id, code, codecap, data.
       id is unique identifier (like 1.001) constructed in an extra step of the
       construction of pwgbib, and in the xml file as an attribute:
       <ls n="1.001">codeX</ls>. 
  there is special 'lshead' element added to xml by basicadjust.
  The css (main.css for webtc) has special font for 'ls' class.
  'is' element (wide spacing)
  There is embedded html  (<lb> or <lb iast="X">) in the abbreviation text.
    This should be removed in the creation step. Currently done in 
    basicadjust.ls_callback.

* v00 generate  pwg 07-09-2018

cd v00
python generate.py pwg inventory.txt  makotemplates ../../pwg/webv00

* TODO Note: there is a special link in webtc/help.html for accents in PWG;
      it points to a subsection of webtc1 help.
* install pwg 
 python install.py pwg ../../pwg/webv00 ../../pwg
* NOTE: pwg webtc2 init_query.py
There was a previous Python version used by PWG (and prob. also by PW).
It is part of the backup, but is not currently used; the 'generic' 
init_query.py is used instead.
* regenerate pwg/web in place  
#in v00
python generate.py pwg inventory.txt  makotemplates ../../pwg/web
* ----------mw---------------------
* NOTES on MW conversion
mwauthtooltips.sqlite, mwab.sqlite
* TODO mwkeys.sqlite  This appears to be unused. Is alphabetical order
still an option in list display?

* generate  mw/webv00 07-13-2018

cd v00
python generate.py mw inventory.txt  makotemplates ../../mw/webv00

* DONE Note: there is a special link in webtc/help.html for accents in MW;
      it points to a subsection of webtc1 help.
* install mw 
 python install.py mw ../../mw/webv00 ../../mw
* NOTE: mw webtc2 init_query.py
There was a previous Python version used by MW (and prob. also by PW).
It is part of the backup, but is not currently used; the 'generic' 
init_query.py is used instead.
* regenerate mw/web in place  
#in v00
python generate.py mw inventory.txt  makotemplates ../../mw/web
* ----------skd---------------------
* NOTES on SKD conversion
 <div n="F">  -- perhaps recode as <F>
* generate  skd/webv00 07-15-2018

cd v00
python generate.py skd inventory.txt  makotemplates ../../skd/webv00

* install skd 
 python install.py skd ../../skd/webv00 ../../skd
* NOTE: skd webtc2 init_query.py
There was a previous Python version used by SKD (and prob. also by PW).
It is part of the backup, but is not currently used; the 'generic' 
init_query.py is used instead.
* regenerate skd/web in place  
#in v00
python generate.py skd inventory.txt  makotemplates ../../skd/web
* ----------ae---------------------
* NOTES on AE conversion

* generate  ae/webv00 07-16-2018

cd v00
python generate.py ae inventory.txt  makotemplates ../../ae/webv00

* install ae 
 python install.py ae ../../ae/webv00 ../../ae
* NOTE: ae webtc2 init_query.py
There was a previous Python version used by AE (and prob. also by PW).
It is part of the backup, but is not currently used; the 'generic' 
init_query.py is used instead.
* regenerate ae/web in place  
#in v00
python generate.py ae inventory.txt  makotemplates ../../ae/web
* ----------pw---------------------
* NOTES on PW conversion
** pwauth  
   This was changed to be like pwg; there is now a pwbib sqlite file
   and the pw.xml generation has a step that adds <ls n="cologneid"> markup
   for linking to pwbib.
   One loss:  the size formatting of the literary source number parts was
      omitted. See webbackup/pw/00/webtc/disp_format_ls.php if desire to
      re-implement it.

* v00 generate  pw 07-19-2018

cd v00
python generate.py pw inventory.txt  makotemplates ../../pw/webv00

* Note: there is a special link in webtc/help.html for accents in PW;
      it points to a subsection of webtc1 help.
* install pw 
 python install.py pw ../../pw/webv00 ../../pw
EXTRA
#cp -r ../../PWGScan/2013/web/fonts/ ../../pw/web/
#cp ../../pw/pywork/pwheader.xml ../../pw/web/
mv ../../pw/web_20180521/sqlite/pwbib.sqlite ../../pw/web/sqlite/pwbib.sqlite 
cd ../../pw/web/webtc2
sh init_query.sh
cd ../../../websanlexicon/v00


* NOTE: pw webtc2 init_query.py
There was a previous Python version used by PW (and prob. also by PW).
It is part of the backup, but is not currently used; the 'generic' 
init_query.py is used instead.
* regenerate pw/web in place  
#in v00
python generate.py pw inventory.txt  makotemplates ../../pw/web
* ----------ap90---------------------
* NOTES on AP90 conversion
  AP90 quirk: recognize "<b>--X</b>" as a line break.  In other dictionaries,
  this would be done with a '<div>' element.
 Also, line breaks '<lb/>' are ignored in the display.
 Also, <P/> tag is changed to <div n="P"/> in basic adjust. Only 7 instances;
   should change in ap90.txt.
* v00 generate  ap90 07-20-2018

cd v00
python generate.py ap90 inventory.txt  makotemplates ../../ap90/webv00

* install ap90 
 python install.py ap90 ../../ap90/webv00 ../../ap90
EXTRA
cp -r ../../pwg/web/fonts/ ../../ap90/web/
#cp ../../ap90/pywork/ap90header.xml ../../ap90/web/
#mv ../../ap90/web_20180521/sqlite/ap90bib.sqlite ../../ap90/web/sqlite/ap90bib.sqlite 
cd ../../ap90/web/webtc2
sh init_query.sh
cd ../../../websanlexicon/v00
* regenerate ap90/web in place  
#in v00
python generate.py ap90 inventory.txt  makotemplates ../../ap90/web

* ----------ap---------------------
* NOTES on AP conversion
 div specialization in disp, with some preparation in basicadjust.
 The 'name' attribute of div tags is unused in display.
 -- replaced by emdash; better in ap.txt?
 Bold Devanagari:
  Look at hari, and the compounds, e.g. -अक्षः.  In the print this is bold.
  There is also logic in sthndl_div to make it bold.
  However, for the change to devanagari, the class sdata_siddhanta is
  interior to the bold tag; and the sdata_siddhanta class has a css
  attribute 'font-weight: normal' which overrides the 'bold'.  End result
  is that अक्षः is normal weight.
  However, if we have output IAST (or anything other than 'deva'), then
  this word IS bold.
  QUESTION: should the 'font-weight: normal' be removed from sdata_siddhanta
  css class?   
--
  Remove '<root/>' tag in basicdisplay code. It is informational, and has
  no special aspect in the printed text.
* v00 generate  ap 07-22-2018
cd v00
python generate.py ap inventory.txt  makotemplates ../../ap/webv00

* install ap 
 python install.py ap ../../ap/webv00 ../../ap
EXTRA
cp -r ../../pwg/web/fonts/ ../../ap/web/
#cp ../../ap/pywork/apheader.xml ../../ap/web/
#mv ../../ap/web_20180521/sqlite/apbib.sqlite ../../ap/web/sqlite/apbib.sqlite 
cd ../../ap/web/webtc2
sh init_query.sh
cd ../../../websanlexicon/v00
* regenerate ap/web in place  
#in v00
python generate.py ap inventory.txt  makotemplates ../../ap/web

* ----------pd---------------------
* NOTES on PD conversion
  only changed sthndl_div.
  Also, tried a change in main_webtc.js (regarding accent) to try to
  avoid a Javascript error that occurs first time through. 
* v00 generate  pd 07-23-2018

cd v00
python generate.py pd inventory.txt  makotemplates ../../pd/webv00

* install pd 
 python install.py pd ../../pd/webv00 ../../pd
EXTRA
#cp -r ../../pwg/web/fonts/ ../../pd/web/
#cp ../../pd/pywork/pdheader.xml ../../pd/web/
#mv ../../pd/web_20180521/sqlite/pdbib.sqlite ../../pd/web/sqlite/pdbib.sqlite 
cd ../../pd/web/webtc2
sh init_query.sh
cd ../../../websanlexicon/v00
* regenerate pd/web in place  
#in v00
python generate.py pd inventory.txt  makotemplates ../../pd/web

* ----------bhs---------------------
* NOTES on BHS conversion
  Probably should change '--' to emdash in bhs.txt
  Placeholders for Greek coded as <lang n="greek"></lang>.

* v00 generate  bhs 07-23-2018

cd v00
python generate.py bhs inventory.txt  makotemplates ../../bhs/webv00

* install bhs 
 python install.py bhs ../../bhs/webv00 ../../bhs
EXTRA
cp -r ../../pwg/web/fonts/ ../../bhs/web/
#cp ../../bhs/pywork/bhsheader.xml ../../bhs/web/
#mv ../../bhs/web_20180521/sqlite/bhsbib.sqlite ../../bhs/web/sqlite/bhsbib.sqlite 
cd ../../bhs/web/webtc2
sh init_query.sh
cd ../../../websanlexicon/v00
* regenerate bhs/web in place  
#in v00
python generate.py bhs inventory.txt  makotemplates ../../bhs/web

* ----------wil---------------------
* NOTES on WIL conversion
  .²1  should change to <div n="..."/> in wil.txt
  Placeholders for Greek coded as <lang n="greek"></lang>.
 Only 1 instance of symbol tag: <symbol n="svastika">卐</symbol>  
   remove symbol tag?
* v00 generate  wil 07-23-2018

cd v00
python generate.py wil inventory.txt  makotemplates ../../wil/webv00

* install wil 
 python install.py wil ../../wil/webv00 ../../wil
EXTRA
cp -r ../../pwg/web/fonts/ ../../wil/web/
#cp ../../wil/pywork/wilheader.xml ../../wil/web/
#mv ../../wil/web_20180521/sqlite/wilbib.sqlite ../../wil/web/sqlite/wilbib.sqlite 
cd ../../wil/web/webtc2
sh init_query.sh
cd ../../../websanlexicon/v00
* regenerate wil/web in place  
#in v00
python generate.py wil inventory.txt  makotemplates ../../wil/web

* ----------yat---------------------
* NOTES on YAT conversion
  yat.xml uses '<br/>' in place of '<div n="lb"/>'
         <g>X</g> (one instance) instead of <lang n="greek">X</lang>
  -- should change to mdash in yat.txt
* v00 generate  yat 07-24-2018

cd v00
python generate.py yat inventory.txt  makotemplates ../../yat/webv00

* install yat 
 python install.py yat ../../yat/webv00 ../../yat
EXTRA
cp -r ../../pwg/web/fonts/ ../../yat/web/
#cp ../../yat/pywork/yatheader.xml ../../yat/web/
#mv ../../yat/web_20180521/sqlite/yatbib.sqlite ../../yat/web/sqlite/yatbib.sqlite 
cd ../../yat/web/webtc2
sh init_query.sh
cd ../../../websanlexicon/v00
* regenerate yat/web in place  
#in v00
python generate.py yat inventory.txt  makotemplates ../../yat/web

* ----------shs---------------------
* NOTES on SHS conversion
  shs.xml uses '<lb/>' in place of '<div n="lb"/>'
  -- should change to mdash in shs.txt
  The 'div' generation of shs.xml is better than that in wil.xml;
   suggest modifying make_xml.py for wil to be more like
   make_xml.py for shs.
  shs is word-for-word the same as wil (examples guru, Gawa).
    Does shs extend WIL in any way?
  Needs revision to modern IAST spelling for proper names (e.g. all caps)
  without diacritics. Also Unadi.
* v00 generate  shs 07-24-2018

cd v00
python generate.py shs inventory.txt  makotemplates ../../shs/webv00

* install shs 
 python install.py shs ../../shs/webv00 ../../shs
EXTRA
cp -r ../../pwg/web/fonts/ ../../shs/web/
#cp ../../shs/pywork/shsheader.xml ../../shs/web/
#mv ../../shs/web_20180521/sqlite/shsbib.sqlite ../../shs/web/sqlite/shsbib.sqlite 
cd ../../shs/web/webtc2
sh init_query.sh
cd ../../../websanlexicon/v00
* regenerate shs/web in place  
#in v00
python generate.py shs inventory.txt  makotemplates ../../shs/web

* ----------gst---------------------
* NOTES on GST conversion
  Several <lang n="greek"></lang> tags.
  <sup> elements made bold.
  The webtc2 query for text strings needs improvement:  Reason applies
   to any dictionary X in which X.xml has line-breaks which separate lines
   with hyphenation. 
* v00 generate  gst 07-24-2018

cd v00
python generate.py gst inventory.txt  makotemplates ../../gst/webv00

* install gst 
 python install.py gst ../../gst/webv00 ../../gst
EXTRA
cp -r ../../pwg/web/fonts/ ../../gst/web/
cp ../../gst/pywork/gstheader.xml ../../gst/web/
#mv ../../gst/web_20180521/sqlite/gstbib.sqlite ../../gst/web/sqlite/gstbib.sqlite 
cd ../../gst/web/webtc2
sh init_query.sh
cd ../../../websanlexicon/v00
* regenerate gst/web in place  
#in v00
python generate.py gst inventory.txt  makotemplates ../../gst/web

* ----------vcp---------------------
* NOTES on VCP conversion
  In vcp.txt:  <P>, <HI>, <H>, <Picture> become <div n="P">" etc. in vcp.xml.
  Also, <> of vcp.txt becomes <lb/> in vcp.xml; 
    Perhaps push the xml codes down into vcp.txt?

* v00 generate  vcp 07-25-2018

cd v00
python generate.py vcp inventory.txt  makotemplates ../../vcp/webv00

* install vcp 
 python install.py vcp ../../vcp/webv00 ../../vcp
EXTRA
cp -r ../../pwg/web/fonts/ ../../vcp/web/
#cp ../../vcp/pywork/vcpheader.xml ../../vcp/web/
#mv ../../vcp/web_20180521/sqlite/vcpbib.sqlite ../../vcp/web/sqlite/vcpbib.sqlite 
cd ../../vcp/web/webtc2
sh init_query.sh
cd ../../../websanlexicon/v00
* regenerate vcp/web in place  
#in v00
python generate.py vcp inventory.txt  makotemplates ../../vcp/web

* ----------ben---------------------
* NOTES on BEN conversion
  <g></g> tag for Greek (empty). Shld change to <lang n="greek"></lang>;
      this done in basicadjust.  (787 lines in ben.xml with <g></g>)
  <pic name="vatsa.png'/> requires vatsa.png in images folder;
  <P/> twice  (headword dIkz and garj):
      indented paragraph. Better to be <div n="P">. Coded this way in 
      basicadjust.
  -- changed to emdash in disp.php. 
  bold section headings -- could be converted to divs for better display.

 Improvement: Move [Pagexxx] at end of entry after <LEND>; this in ben.txt.
* v00 generate  ben 07-25-2018

cd v00
python generate.py ben inventory.txt  makotemplates ../../ben/webv00

* install ben 
 python install.py ben ../../ben/webv00 ../../ben
EXTRA
cp -r ../../pwg/web/fonts/ ../../ben/web/
#cp ../../ben/pywork/benheader.xml ../../ben/web/
cp ../../ben/web_20170410/images/vatsa.png ../../ben/web/images/
cd ../../ben/web/webtc2
sh init_query.sh
cd ../../../websanlexicon/v00
* regenerate ben/web in place  
#in v00
python generate.py ben inventory.txt  makotemplates ../../ben/web

* ----------bop---------------------
* NOTES on BOP conversion
  

* v00 generate  bop 07-25-2018

cd v00
python generate.py bop inventory.txt  makotemplates ../../bop/webv00

* install bop 
 python install.py bop ../../bop/webv00 ../../bop
EXTRA
cp -r ../../pwg/web/fonts/ ../../bop/web/
#cp ../../bop/pywork/bopheader.xml ../../bop/web/
#mv ../../bop/web_20180521/sqlite/bopbib.sqlite ../../bop/web/sqlite/bopbib.sqlite 
cd ../../bop/web/webtc2
sh init_query.sh
cd ../../../websanlexicon/v00
* regenerate bop/web in place  
#in v00
python generate.py bop inventory.txt  makotemplates ../../bop/web

* ----------bor---------------------
* NOTES on BOR conversion
  Part of the 'div' adjustment (that done in basicadjust) maybe should
   be done either in bor.xml or bor.txt.

* v00 generate  bor 07-25-2018

cd v00
python generate.py bor inventory.txt  makotemplates ../../bor/webv00

* install bor 
 python install.py bor ../../bor/webv00 ../../bor
EXTRA
cp -r ../../pwg/web/fonts/ ../../bor/web/
#cp ../../bor/pywork/borheader.xml ../../bor/web/
#mv ../../bor/web_20180521/sqlite/borbib.sqlite ../../bor/web/sqlite/borbib.sqlite 
cd ../../bor/web/webtc2
sh init_query.sh
cd ../../../websanlexicon/v00
* regenerate bor/web in place  
#in v00
python generate.py bor inventory.txt  makotemplates ../../bor/web

* ----------ccs---------------------
* NOTES on CCS conversion
  Part of the 'div' adjustment (that done in basicadjust) maybe should
   be done either in ccs.xml or ccs.txt.

* v00 generate  ccs 07-26-2018

cd v00
python generate.py ccs inventory.txt  makotemplates ../../ccs/webv00

* install ccs 
 python install.py ccs ../../ccs/webv00 ../../ccs
EXTRA
#cp -r ../../pwg/web/fonts/ ../../ccs/web/
#cp ../../ccs/pywork/ccsheader.xml ../../ccs/web/
cd ../../ccs/web/webtc2
sh init_query.sh
cd ../../../websanlexicon/v00
* regenerate ccs/web in place  
#in v00
python generate.py ccs inventory.txt  makotemplates ../../ccs/web

* ----------md---------------------
* NOTES on MD conversion
* v00 generate  md 07-26-2018

cd v00
python generate.py md inventory.txt  makotemplates ../../md/webv00

* install md 
 python install.py md ../../md/webv00 ../../md
EXTRA
cp -r ../../pwg/web/fonts/ ../../md/web/
#cp ../../md/pywork/mdheader.xml ../../md/web/
cd ../../md/web/webtc2
sh init_query.sh
cd ../../../websanlexicon/v00
* regenerate md/web in place  
#in v00
python generate.py md inventory.txt  makotemplates ../../md/web

* ----------mwe---------------------
* NOTES on MWE conversion
* v00 generate  mwe 07-26-2018

cd v00
python generate.py mwe inventory.txt  makotemplates ../../mwe/webv00

* install mwe 
 python install.py mwe ../../mwe/webv00 ../../mwe
EXTRA
cp -r ../../pwg/web/fonts/ ../../mwe/web/
#cp ../../mwe/pywork/mweheader.xml ../../mwe/web/
cd ../../mwe/web/webtc2
sh init_query.sh
cd ../../../websanlexicon/v00
* regenerate mwe/web in place  
#in v00
python generate.py mwe inventory.txt  makotemplates ../../mwe/web

* ----------mw72---------------------
* NOTES on MW72 conversion
  The <lang> tag is sometimes filled in with unicode, sometimes not.
  Add (temporary) code in basicadjust with attribute empty="yes": e.g.
    <lang n="greek" empty="yes"></lang>
  And use this in sthndl of disp.php.

  <nsi> tag no display

* v00 generate  mw72 07-26-2018

cd v00
python generate.py mw72 inventory.txt  makotemplates ../../mw72/webv00

* install mw72 
 python install.py mw72 ../../mw72/webv00 ../../mw72
EXTRA
cp -r ../../pwg/web/fonts/ ../../mw72/web/
#cp ../../mw72/pywork/mw72header.xml ../../mw72/web/
cd ../../mw72/web/webtc2
sh init_query.sh
cd ../../../websanlexicon/v00
* regenerate mw72/web in place  
#in v00
python generate.py mw72 inventory.txt  makotemplates ../../mw72/web

* ----------ieg---------------------
* NOTES on IEG conversion
  
* v00 generate  ieg 07-26-2018

cd v00
python generate.py ieg inventory.txt  makotemplates ../../ieg/webv00

* install ieg 
 python install.py ieg ../../ieg/webv00 ../../ieg
EXTRA
cp -r ../../pwg/web/fonts/ ../../ieg/web/
#cp ../../ieg/pywork/iegheader.xml ../../ieg/web/
cd ../../ieg/web/webtc2
sh init_query.sh
cd ../../../websanlexicon/v00
* regenerate ieg/web in place  
#in v00
python generate.py ieg inventory.txt  makotemplates ../../ieg/web


* ----------inm---------------------
* NOTES on INM conversion
  
* v00 generate  inm 07-26-2018

cd v00
python generate.py inm inventory.txt  makotemplates ../../inm/webv00

* install inm 
 python install.py inm ../../inm/webv00 ../../inm
EXTRA
cp -r ../../pwg/web/fonts/ ../../inm/web/
#cp ../../inm/pywork/inmheader.xml ../../inm/web/
cd ../../inm/web/webtc2
sh init_query.sh
cd ../../../websanlexicon/v00
* regenerate inm/web in place  
#in v00
python generate.py inm inventory.txt  makotemplates ../../inm/web


* ----------krm---------------------
* NOTES on KRM conversion
  
* v00 generate  krm 07-26-2018

cd v00
python generate.py krm inventory.txt  makotemplates ../../krm/webv00

* install krm 
 python install.py krm ../../krm/webv00 ../../krm
EXTRA
cp -r ../../pwg/web/fonts/ ../../krm/web/
#cp ../../krm/pywork/krmheader.xml ../../krm/web/
cd ../../krm/web/webtc2
sh init_query.sh
cd ../../../websanlexicon/v00
* regenerate krm/web in place  
#in v00
python generate.py krm inventory.txt  makotemplates ../../krm/web

* ----------mci---------------------
* NOTES on MCI conversion
  
* v00 generate  mci 07-26-2018

cd v00
python generate.py mci inventory.txt  makotemplates ../../mci/webv00

* install mci 
 python install.py mci ../../mci/webv00 ../../mci
EXTRA
cp -r ../../pwg/web/fonts/ ../../mci/web/
#cp ../../mci/pywork/mciheader.xml ../../mci/web/
cd ../../mci/web/webtc2
sh init_query.sh
cd ../../../websanlexicon/v00
* regenerate mci/web in place  
#in v00
python generate.py mci inventory.txt  makotemplates ../../mci/web


* ----------pe---------------------
* NOTES on PE conversion
  This is a line-by-line digitization.  Hyphenations not resolved.
  There are some {??} unreadable text items.
* v00 generate  pe 07-27-2018

cd v00
python generate.py pe inventory.txt  makotemplates ../../pe/webv00

* install pe 
 python install.py pe ../../pe/webv00 ../../pe
EXTRA
cp -r ../../pwg/web/fonts/ ../../pe/web/
#cp ../../pe/pywork/peheader.xml ../../pe/web/
cd ../../pe/web/webtc2
sh init_query.sh
cd ../../../websanlexicon/v00
* regenerate pe/web in place  
#in v00
python generate.py pe inventory.txt  makotemplates ../../pe/web


* ----------pgn---------------------
* NOTES on PGN conversion
  
* v00 generate  pgn 07-27-2018

cd v00
python generate.py pgn inventory.txt  makotemplates ../../pgn/webv00

* install pgn 
 python install.py pgn ../../pgn/webv00 ../../pgn
EXTRA
cp -r ../../pwg/web/fonts/ ../../pgn/web/
#cp ../../pgn/pywork/pgnheader.xml ../../pgn/web/
cd ../../pgn/web/webtc2
sh init_query.sh
cd ../../../websanlexicon/v00
* regenerate pgn/web in place  
#in v00
python generate.py pgn inventory.txt  makotemplates ../../pgn/web


* ----------pui---------------------
* NOTES on PUI conversion
  pui.txt is line by line. Hyphenated lines not resolved.
  <div n="P"/> is used in two ways.  Most introduce a section of references at
  the end of entries; these don't need indenting.  Fewer others introduce
  additional paragraphs, and should be indented.  
  The current markup and displays do not recognize this distinction:
  <div n="P"/> and <div n="lb"/> are both displayed as simple line breaks.
  In revised version v00, I've indented the 'P', of whichever of the two kinds.

  No Devanagari in print;  in digitization, key1 form of headword is in slp1
  representation of Devanagari.  Perhaps change wording in Adv. Search for
  'Sanskrit word'
* v00 generate  pui 07-28-2018

cd v00
python generate.py pui inventory.txt  makotemplates ../../pui/webv00

* install pui 
 python install.py pui ../../pui/webv00 ../../pui
EXTRA
cp -r ../../pwg/web/fonts/ ../../pui/web/
#cp ../../pui/pywork/puiheader.xml ../../pui/web/
cd ../../pui/web/webtc2
sh init_query.sh
cd ../../../websanlexicon/v00
* regenerate pui/web in place  
#in v00
python generate.py pui inventory.txt  makotemplates ../../pui/web


* ----------sch---------------------
* NOTES on SCH conversion
  No Devanagari in print;  in digitization, key1 form of headword is in slp1
  representation of Devanagari.  Perhaps change wording in Adv. Search for
  'Sanskrit word'
  
  <div>X</div> coding used in sch.xml.  No attribute to div tag.

  The 'key2' is not part of body: This should be changed in sch.txt.
  Also, the <type>*</type> tag appears at end, while it should precede
  the key2.  A crude step in this direction is used in 'chrhndl' in disp.php.
  Better would be to change sch.txt in <body> to show : <type>*</type> {key2-iast}
  
  Superscripts are shown as '^x'.  Should recode as <sup>x</sup> in sch.txt.
    Altered basicadjust to do this transform.
* v00 generate  sch 07-28-2018

cd v00
python generate.py sch inventory.txt  makotemplates ../../sch/webv00

* install sch 
 python install.py sch ../../sch/webv00 ../../sch
EXTRA
cp -r ../../pwg/web/fonts/ ../../sch/web/
#cp ../../sch/pywork/schheader.xml ../../sch/web/
cd ../../sch/web/webtc2
sh init_query.sh
cd ../../../websanlexicon/v00
* regenerate sch/web in place  
#in v00
python generate.py sch inventory.txt  makotemplates ../../sch/web


* ----------snp---------------------
* NOTES on SNP conversion
  Corrected a bug in smatchkey of querymodel.php in webtc2 -- the error
     prevented matches with the FIRST record of query_dump.txt.  This
     error applies to all dictionaries, so they all need to be updated.
     (via redo_web_all.sh or redo_cologne_all.sh).
* v00 generate  snp 07-28-2018

cd v00
python generate.py snp inventory.txt  makotemplates ../../snp/webv00

* install snp 
 python install.py snp ../../snp/webv00 ../../snp
EXTRA
cp -r ../../pwg/web/fonts/ ../../snp/web/
#cp ../../snp/pywork/snpheader.xml ../../snp/web/
cd ../../snp/web/webtc2
sh init_query.sh
cd ../../../websanlexicon/v00
* regenerate snp/web in place  
#in v00
python generate.py snp inventory.txt  makotemplates ../../snp/web

* ----------vei---------------------
* NOTES on VEI conversion
  Footnote:  line break before AND after;  previous display only 
     breaks before.  This could be changed by dictionary specific
     code in endhndl (of webtc/disp.php)
* v00 generate  vei 07-28-2018

cd v00
python generate.py vei inventory.txt  makotemplates ../../vei/webv00

* install vei 
 python install.py vei ../../vei/webv00 ../../vei
EXTRA
cp -r ../../pwg/web/fonts/ ../../vei/web/
#cp ../../vei/pywork/veiheader.xml ../../vei/web/
cd ../../vei/web/webtc2
sh init_query.sh
cd ../../../websanlexicon/v00
* regenerate vei/web in place  
#in v00
python generate.py vei inventory.txt  makotemplates ../../vei/web


* ----------acc---------------------
* NOTES on ACC conversion
  <symbol n="C."/>C.</symbol>   used to code a backwards C:
  Maybe this is just an abbreviation for 'Commentary' ?
* v00 generate  acc 07-28-2018

cd v00
python generate.py acc inventory.txt  makotemplates ../../acc/webv00

* install acc 
 python install.py acc ../../acc/webv00 ../../acc
EXTRA
cp -r ../../pwg/web/fonts/ ../../acc/web/
#cp ../../acc/pywork/accheader.xml ../../acc/web/
cd ../../acc/web/webtc2
sh init_query.sh
cd ../../../websanlexicon/v00
* regenerate acc/web in place  
#in v00
python generate.py acc inventory.txt  makotemplates ../../acc/web
* --------------------------------------------------------------
* redo_web_all.sh
 in v00
 gra, bur, cae, stc, pwg, mw, skd, ae, 
 pw, ap90, ap,  pd,  bhs, wil, yat, shs,
 gst, vcp, ben, bop, bor, ccs, md, mwe,
mw72, ieg, inm, krm, mci, pe, pgn, pui,

sch, snp, vei, acc
* --------------------------------------------------------------
* apidev
* --------------------------------------------------------------
* copy modules from webtc, and modify for apidev.
** previous copies in apidev
cp basicadjust.php.php temp_prev_basicadjust.php
cp basicadjust.php temp_prev_basicadjust.php
cp basicdisplay.php temp_prev_basicdisplay.php

** dalraw
cp v00/makotemplates/webtc/dal.php ../apidev/dalraw.php
# also, change class name to Dalraw
** basicadjust
cp v00/makotemplates/webtc/basicadjust.php ../apidev/basicadjust.php
additional changes: 
 a) dal.php -> dalraw.php (one)
 b) new Dal -> new Dalraw (three or more)
** basicdisplay 
cp v00/makotemplates/webtc/disp.php ../apidev/basicdisplay.php
# no additional changes

** modify apidev/dalwhich.php
  for dictionaries that have been 'converted'.

* THE END



