
Install web applications
version 0.1 
2018-07-01
This documentation is best viewed with Emacs, as it uses the 'org mode'.

The paths in this readme assume the organization of web directories
as in the Cologne web site.  The web directory for dictionary 'X' is, relative
to the directory of this websanlexicon directory, ../XScan/YEAR/web
where YEAR is different for different scans.  The YEAR corresponding to a 
given dictionary X is given in this table:

* Cologne dictionary years
   array("ACC"=>"2014" , "AE"=>"2014" , "AP"=>"2014" , "AP90"=>"2014",
       "BEN"=>"2014" , "BHS"=>"2014" , "BOP"=>"2014" , "BOR"=>"2014",
       "BUR"=>"2013" , "CAE"=>"2014" , "CCS"=>"2014" , "GRA"=>"2014",
       "GST"=>"2014" , "IEG"=>"2014" , "INM"=>"2013" , "KRM"=>"2014",
       "MCI"=>"2014" , "MD"=>"2014" , "MW"=>"2014" , "MW72"=>"2014",
       "MWE"=>"2013" , "PD"=>"2014" , "PE"=>"2014" , "PGN"=>"2014",
       "PUI"=>"2014" , "PWG"=>"2013" , "PW"=>"2014" , "SCH"=>"2014",
       "SHS"=>"2014" , "SKD"=>"2013" , "SNP"=>"2014" , "STC"=>"2013",
       "VCP"=>"2013" , "VEI"=>"2014" , "WIL"=>"2014" , "YAT"=>"2014");

* mako
  The generate.py code is intended to work with Python 2;  it was developed
  on ejf local machine with Python 2.7.10, and mako version 1.0.6.
  The cologne version of python 2  (2.6.6) had an old version (0.3.4) of 
  mako which threw an exception regarding Unicode conversion.
  Solution:   from https://pypi.org/project/Mako/1.0.7/#files,  
    the 1.0.7 version of mako was downloaded.  When extracted, there
    was a single 'mako' folder, that contains only Python code.
    This folder was zipped and copied to Cologne and put in the v00
    folder.  Now, when python generate.py ... is run in v00,  the 1.0.7
    version of mako is what is used., and it works fine.
* inventory
Directories and files in web application subdirectories, specifically for 'gra'
** web directory files
graheader.xml
index.php
readme.txt

** images
images/cologne_univ_seal.gif
images/encoding.gif
** js
js/jquery.cookie.js
js/jquery.min.js
** mobile1
mobile1/index.php
mobile1/main.css
mobile1/main_mobile.js
mobile1/monier_serveimg.css
** sqlite
sqlite/def.sql
sqlite/gra.sqlite
sqlite/input.txt
sqlite/make_input.php
sqlite/redo.sh
** utilities
transcoder.php
** utilities/transcoder
utilities/transcoder/as_roman.xml
utilities/transcoder/deva_slp1.xml
utilities/transcoder/hk_slp1.xml
utilities/transcoder/itrans_slp1.xml
utilities/transcoder/roman_slp1.xml
utilities/transcoder/slp1_as.xml
utilities/transcoder/slp1_deva.xml
utilities/transcoder/slp1_hk.xml
utilities/transcoder/slp1_itrans.xml
utilities/transcoder/slp1_roman.xml
utilities/transcoder/slp1_romanpms.xml
utilities/transcoder/slp1_wx.xml
utilities/transcoder/wx_slp1.xml
** webtc
webtc/basicadjust.php
webtc/dal.php
webtc/dbgprint.php
webtc/dictcode.php
webtc/dictinfo.php
webtc/disp.php
webtc/download.html
webtc/getword.php
webtc/getwordviewmodel.php
webtc/help.html
webtc/indexcaller.php
webtc/main.css
webtc/main_webtc.js
webtc/parm.php
webtc/pdffiles.txt
webtc/serveimg.css
webtc/servepdf.php
webtc/translithelp.html
** webtc1
webtc1/disphier.php
webtc1/index.php
webtc1/keyboard.css
webtc1/keyboard.js
webtc1/keyboard.png
webtc1/listhier.php
webtc1/listhiermodel.php
webtc1/listhierview.php
webtc1/listparm.php
webtc1/main.css
webtc1/main.js
webtc1/preferences.htm
webtc1/transcoderfield_VKI.js
** webtc1/help
webtc1/help/accents.html
webtc1/help/ack.html
webtc1/help/definition.html
webtc1/help/help.css
webtc1/help/help.html
webtc1/help/help.js
webtc1/help/helpmain.html
** webtc1/help/images
webtc1/help/images/input.html
webtc1/help/images/keyboard.html
webtc1/help/images/links.html
webtc1/help/images/list.html
webtc1/help/images/phonetic.html
webtc1/help/images/preferences.html
webtc1/help/images/system.html
** webtc1/transcoderjs
webtc1/transcoderjs/transcoder3.js
webtc1/transcoderjs/transcoderJson.js
** webtc2
webtc2/help.html
webtc2/index.php
webtc2/init_query.php
webtc2/init_query.sh
webtc2/main.css
webtc2/main.js
webtc2/query.php
webtc2/query_dump.txt
webtc2/query_gather.php
webtc2/query_multi.php
webtc2/querylistview.php
webtc2/querymodel.php
webtc2/queryparm.php

** not included
mobile1/old:
utilities/old:
utilities/transcoder/old:
utilities/transcoder/pms:
webtc/old:
webtc1/old:
webtc1/old1:
webtc2/old:
webtc2/old1:
* INSTALLING:
** directories which are same for all dictionaries
 images, 
 js, 
 utilities, utilities/transcoder,
 webtc1/help webtc1/help/images, webtc1/transcoderjs
** sqlite directory
   def.sql, make_input.php, and redo.sh are used to generate
   gra.sqlite from gra.xml.
   input.txt is an intermediate file.
   Only gra.sqlite is used by displays.
   For some other dictionaries, xab.sqlite and xauth.sqlite are used
   by displays.
 The data constructors in webtc need to know where the sqlite database
 files reside, and their name and table names. e.g. gra.sqlite has table
 named gra.
 Other tables could be put into gra.sqlite, but this is not done now.
 The current convention is that if X.sqlite is the filename, then the
 table name is X  (e.g. whitmwtab.sqlite has table name whitmwtab.)
* webtc2/query_dump.txt
* next
* backup an inventory file
 refer to readme_xampp.org.
 These backups are being done on local computer, and are thus part of
 the repository.  No need to repeat this step on Cologne server.

* v00 -- initial 'general' version of web
  starts as a copy of webbackup/gra/00
* install datafiles to move
pdfpages # directory
fonts    # directory
sqlite/gra.sqlite 
sqlite/graab.sqlite
sqlite/gramwauth.sqlite
webtc2/query_dump.txt
webtc/pdffiles.txt

* -------------- gra
* v00 generate and install: gra
cd v00
python generate.py gra inventory.txt  makotemplates ../../GRAScan/2014/webv00


# python install.py <dictcode> <dirin> <diroutparent>
 python install.py gra ../../GRAScan/2014/webv00 ../../GRAScan/2014

Extra: (for siddhanta)
 cp -r ../../PWGScan/2013/web/fonts/ ../../GRAScan/2014/web/

* regenerate gra in place  (modifies 'web' directly)
#in v00
python generate.py gra inventory.txt  makotemplates ../../GRAScan/2014/web

* -------------- bur
* v00 generate and install: bur
cd v00
python generate.py bur inventory.txt  makotemplates ../../BURScan/2013/webv00

# python install.py <dictcode> <dirin> <diroutparent>
 python install.py bur ../../BURScan/2013/webv00 ../../BURScan/2013
Extra: (for siddhanta)
 cp -r ../../PWGScan/2013/web/fonts/ ../../BURScan/2013/web/

cd ../../BURScan/2013/web/webtc2
sh init_query.sh

cp ../../BURScan/2013/pywork/burheader.xml ../../BURScan/2013/web/

* regenerate bur in place  (modifies 'web' directly)
#in v00
python generate.py bur inventory.txt  makotemplates ../../BURScan/2013/web
* TODO 'outopt' in webtc2
  This is vestigial.  Needs to be removed in several places:
    main.js, queryParm.php, index.php, elsewhere?
* TODO modifyDeva in main.js
  Is this the right way to insure Siddhanta font for devanagari output?
* DONE accent
  This is a display option. Implement in BasicAdjust? 
  Currently a parameter in query_multi.php
* TODO webtc2/querymodel.php case problem
In searching for normal text, the text is converted to lower case using
mb_strtolower function.  However, this does not always work in the the
same way the the '.lower()' string method of Python works.
For instance, a search for Śiva yields no results, while śiva succeeds.

* ----------cae---------------------
* v00 generate and install: cae
cd v00
python generate.py cae inventory.txt  makotemplates ../../CAEScan/2014/webv00

#python generate.py cae temp_inventory.txt  temp_templates tempdir

# python install.py <dictcode> <dirin> <diroutparent>
 python install.py cae ../../CAEScan/2014/webv00 ../../CAEScan/2014

EXTRA:
cp ../../CAEScan/2014/pywork/caeheader.xml ../../CAEScan/2014/web/

cd ../../CAEScan/2014/web/webtc2
sh init_query.sh

* regenerate cae in place  (modifies 'web' directly)
#in v00
python generate.py cae inventory.txt  makotemplates ../../CAEScan/2014/web
* Use siddhanta font
* ----------stc---------------------
* v00 generate  stc 07-08-2018
This is peculiar, because there are Frenchified versions of some displays:
webtc/download_fr.html , help_fr.html , indexcaller_fr.php
These are processed by generate.py as additional inventory files.

cd v00
python generate.py stc inventory.txt  makotemplates ../../STCScan/2013/webv00

* install stc 07-08-2018
 python install.py stc ../../STCScan/2013/webv00 ../../STCScan/2013
 
 EXTRA:
 cp -r ../../PWGScan/2013/web/fonts/ ../../STCScan/2013/web/
cp ../../STCScan/2013/pywork/stcheader.xml ../../STCScan/2013/web/

cd ../../STCScan/2013/web/webtc2
sh init_query.sh

cp ../../STCScan/2013/web_20140623/index_fr.php ../../STCScan/2013/web/

* TODO  put front matter, etc. into web/index_fr.php

* regenerate stc/web in place  
#in v00
python generate.py stc inventory.txt  makotemplates ../../STCScan/2013/web
* ----------pwg---------------------
* NOTES on PWG conversion
** pwgauth  
   This is first dictionary conversion with links resolving ls (works/authors)
   sqlite file named pwgbib  (why not pwgauth?) -- basicadjust.php
      structure: id, code, codecap, data.
       id is unique identifier (like 1.001) constructed in an extra step of the
       construction of pwgbib, and in the xml file as an attribute:
       <ls n="1.001">codeX</ls>. 
  there is special 'lshead' element added to xml by basicadjust.
  The css (main.css for webtc) has special font for 'ls' class.
  'is' element (wide spacing)
  There is embedded html  (<lb> or <lb iast="X">) in the abbreviation text.
    This should be removed in the creation step. Currently done in 
    basicadjust.ls_callback.

* v00 generate  pwg 07-09-2018

cd v00
python generate.py pwg inventory.txt  makotemplates ../../PWGScan/2013/webv00

* Note: there is a special link in webtc/help.html for accents in PWG;
      it points to a subsection of webtc1 help.
* install pwg 
 python install.py pwg ../../PWGScan/2013/webv00 ../../PWGScan/2013

EXTRA:
cp ../../PWGScan/2013/pywork/pwgheader.xml ../../PWGScan/2013/web/

cd ../../PWGScan/2013/web/webtc2
sh init_query.sh

* NOTE: pwg webtc2 init_query.py
There was a previous Python version used by PWG (and prob. also by PW).
It is part of the backup, but is not currently used; the 'generic' 
init_query.py is used instead.
* regenerate pwg/web in place  
#in v00
python generate.py pwg inventory.txt  makotemplates ../../PWGScan/2013/web
* ----------mw---------------------
* NOTES on MW conversion
mwauthtooltips.sqlite, mwab.sqlite
* TODO mwkeys.sqlite  This appears to be unused. Is alphabetical order
still an option in list display?

* generate  mw/webv00 07-13-2018

cd v00
python generate.py mw inventory.txt  makotemplates ../../MWScan/2014/webv00

* DONE Note: there is a special link in webtc/help.html for accents in MW;
      it points to a subsection of webtc1 help.
* install mw 
 python install.py mw ../../MWScan/2014/webv00 ../../MWScan/2014

EXTRA:
cp ../../MWScan/2014/pywork/mwheader.xml ../../MWScan/2014/web/

cd ../../MWScan/2014/web/webtc2
sh init_query.sh

* regenerate mw/web in place  
#in v00
python generate.py mw inventory.txt  makotemplates ../../MWScan/2014/web
* ----------skd---------------------
* NOTES on SKD conversion
 <div n="F">  -- perhaps recode as <F>
* generate  skd/webv00 07-15-2018

cd v00
python generate.py skd inventory.txt  makotemplates ../../SKDScan/2013/webv00

* install skd 
 python install.py skd ../../SKDScan/2013/webv00 ../../SKDScan/2013

EXTRA:
 cp -r ../../PWGScan/2013/web/fonts/ ../../SKDScan/2013/web/
cp ../../SKDScan/2013/pywork/skdheader.xml ../../SKDScan/2013/web/
cd ../../SKDScan/2013/web/webtc2
sh init_query.sh
cd ../../../../websanlexicon/v00

* regenerate skd/web in place  
#in v00
python generate.py skd inventory.txt  makotemplates ../../SKDScan/2013/web
* ----------ae---------------------
* NOTES on AE conversion

* generate  ae/webv00 07-16-2018

cd v00
python generate.py ae inventory.txt  makotemplates ../../AEScan/2014/webv00

* install ae 
 python install.py ae ../../AEScan/2014/webv00 ../../AEScan/2014
EXTRA:
cp -r ../../PWGScan/2013/web/fonts/ ../../AEScan/2014/web/
cp ../../AEScan/2014/pywork/aeheader.xml ../../AEScan/2014/web/
cd ../../AEScan/2014/web/webtc2
sh init_query.sh
cd ../../../../websanlexicon/v00

* regenerate ae/web in place  
#in v00
python generate.py ae inventory.txt  makotemplates ../../AEScan/2014/web
* ----------pw---------------------
* NOTES on PW conversion
** pwauth  
   This was changed to be like pwg; there is now a pwbib sqlite file
   and the pw.xml generation has a step that adds <ls n="cologneid"> markup
   for linking to pwbib.
   One loss:  the size formatting of the literary source number parts was
      omitted. See webbackup/pw/00/webtc/disp_format_ls.php if desire to
      re-implement it.

* v00 generate  pw 07-19-2018

cd v00
python generate.py pw inventory.txt  makotemplates ../../PWScan/2014/webv00

* Note: there is a special link in webtc/help.html for accents in PW;
      it points to a subsection of webtc1 help.
* install pw 
 python install.py pw ../../PWScan/2014/webv00 ../../PWScan/2014
EXTRA:
#cp -r ../../PWGScan/2013/web/fonts/ ../../PWScan/2014/web/
cp ../../PWScan/2014/pywork/pwheader.xml ../../PWScan/2014/web/
mv ../../PWScan/2014/web_20140628/sqlite/pwbib.sqlite ../../PWScan/2014/web/sqlite/pwbib.sqlite 
cd ../../PWScan/2014/web/webtc2
sh init_query.sh
cd ../../../../websanlexicon/v00

* regenerate pw/web in place  
#in v00
python generate.py pw inventory.txt  makotemplates ../../PWScan/2014/web
* ----------ap90---------------------
* NOTES on AP90 conversion
  AP90 quirk: recognize "<b>--X</b>" as a line break.  In other dictionaries,
  this would be done with a '<div>' element.
 Also, line breaks '<lb/>' are ignored in the display.
 Also, <P/> tag is changed to <div n="P"/> in basic adjust. Only 7 instances;
   should change in ap90.txt.
* v00 generate  ap90 07-22-2018

cd v00
python generate.py ap90 inventory.txt  makotemplates ../../AP90Scan/2014/webv00

* install ap90 
 python install.py ap90 ../../AP90Scan/2014/webv00 ../../AP90Scan/2014
EXTRA
cp -r ../../PWGScan/2013/web/fonts/ ../../AP90Scan/2014/web/
cp ../../AP90Scan/2014/pywork/ap90header.xml ../../AP90Scan/2014/web/
#mv ../../AP90Scan/2014/web_20180521/sqlite/ap90bib.sqlite ../../AP90Scan/2014/web/sqlite/ap90bib.sqlite 
cd ../../AP90Scan/2014/web/webtc2
sh init_query.sh
cd ../../../../websanlexicon/v00
* regenerate ap90/web in place  
#in v00
python generate.py ap90 inventory.txt  makotemplates ../../AP90Scan/2014/web

* ----------ap---------------------
* NOTES on AP conversion
  AP quirk: recognize "<b>--X</b>" as a line break.  In other dictionaries,
  this would be done with a '<div>' element.
 Also, line breaks '<lb/>' are ignored in the display.
 Also, <P/> tag is changed to <div n="P"/> in basic adjust. Only 7 instances;
   should change in ap.txt.
* v00 generate  ap 07-22-2018

cd v00
python generate.py ap inventory.txt  makotemplates ../../APScan/2014/webv00

* install ap 
 python install.py ap ../../APScan/2014/webv00 ../../APScan/2014
EXTRA
#cp -r ../../PWGScan/2013/web/fonts/ ../../APScan/2014/web/
cp ../../APScan/2014/pywork/apheader.xml ../../APScan/2014/web/
#mv ../../APScan/2014/web_20180521/sqlite/apbib.sqlite ../../APScan/2014/web/sqlite/apbib.sqlite 
cd ../../APScan/2014/web/webtc2
sh init_query.sh
cd ../../../../websanlexicon/v00
* regenerate ap/web in place  
#in v00
python generate.py ap inventory.txt  makotemplates ../../APScan/2014/web

* ----------pd---------------------
* NOTES on PD conversion
  only changed sthndl_div.
  Also, tried a change in main_webtc.js (regarding accent) to try to
  avoid a Javascript error that occurs first time through. 
* v00 generate  pd 07-23-2018

cd v00
python generate.py pd inventory.txt  makotemplates ../../PDScan/2014/webv00

* install pd 
 python install.py pd ../../PDScan/2014/webv00 ../../PDScan/2014
EXTRA
#cp -r ../../pwg/web/fonts/ ../../PDScan/2014/web/
cp ../../PDScan/2014/pywork/pdheader.xml ../../PDScan/2014/web/
#mv ../../PDScan/2014/web_20180521/sqlite/pdbib.sqlite ../../PDScan/2014/web/sqlite/pdbib.sqlite 
cd ../../PDScan/2014/web/webtc2
sh init_query.sh
cd ../../../../websanlexicon/v00
* regenerate pd/web in place  
#in v00
python generate.py pd inventory.txt  makotemplates ../../PDScan/2014/web

* ----------bhs---------------------
* NOTES on BHS conversion
  Probably should change '--' to emdash in bhs.txt
  Placeholders for Greek coded as <lang n="greek"></lang>.

* v00 generate  bhs 07-23-2018

cd v00
python generate.py bhs inventory.txt  makotemplates ../../BHSScan/2014/webv00

* install bhs 
 python install.py bhs ../../BHSScan/2014/webv00 ../../BHSScan/2014
EXTRA
cp -r ../../PWGScan/2013/web/fonts/ ../../BHSScan/2014/web/
cp ../../BHSScan/2014/pywork/bhsheader.xml ../../BHSScan/2014/web/
#mv ../../BHSScan/2014/web_20180521/sqlite/bhsbib.sqlite ../../BHSScan/2014/web/sqlite/bhsbib.sqlite 
cd ../../BHSScan/2014/web/webtc2
sh init_query.sh
cd ../../../../websanlexicon/v00
* regenerate bhs/web in place  
#in v00
python generate.py bhs inventory.txt  makotemplates ../../BHSScan/2014/web

* ----------wil---------------------
* NOTES on WIL conversion
  .²1  should change to <div n="..."/> in wil.txt
  Placeholders for Greek coded as <lang n="greek"></lang>.
 Only 1 instance of symbol tag: <symbol n="svastika">卐</symbol>  
   remove symbol tag?
* v00 generate  wil 07-23-2018

cd v00
python generate.py wil inventory.txt  makotemplates ../../WILScan/2014/webv00

* install wil 
 python install.py wil ../../WILScan/2014/webv00 ../../WILScan/2014
EXTRA
 cp -r ../../PWGScan/2013/web/fonts/ ../../WILScan/2014/web/
cp ../../WILScan/2014/pywork/wilheader.xml ../../WILScan/2014/web/
#mv ../../WILScan/2014/web_20180521/sqlite/wilbib.sqlite ../../WILScan/2014/web/sqlite/wilbib.sqlite 
cd ../../WILScan/2014/web/webtc2
sh init_query.sh
cd ../../../../websanlexicon/v00
* regenerate wil/web in place  
#in v00
python generate.py wil inventory.txt  makotemplates ../../WILScan/2014/web

* ----------yat---------------------
* NOTES on YAT conversion
  yat.xml uses '<br/>' in place of '<div n="lb"/>'
         <g>X</g> (one instance) instead of <lang n="greek">X</lang>
  -- should change to mdash in yat.txt
* v00 generate  yat 07-24-2018

cd v00
python generate.py yat inventory.txt  makotemplates ../../YATScan/2014/webv00

* install yat 
 python install.py yat ../../YATScan/2014/webv00 ../../YATScan/2014
EXTRA
cp -r ../../PWGScan/2013/web/fonts/ ../../YATScan/2014/web/
cp ../../YATScan/2014/pywork/yatheader.xml ../../YATScan/2014/web/
#mv ../../YATScan/2014/web_20180521/sqlite/yatbib.sqlite ../../YATScan/2014/web/sqlite/yatbib.sqlite 
cd ../../YATScan/2014/web/webtc2
sh init_query.sh
cd ../../../../websanlexicon/v00
* regenerate yat/web in place  
#in v00
python generate.py yat inventory.txt  makotemplates ../../YATScan/2014/web

* ----------shs---------------------
* NOTES on SHS conversion
  shs.xml uses '<lb/>' in place of '<div n="lb"/>'
  -- should change to mdash in shs.txt
  The 'div' generation of shs.xml is better than that in wil.xml;
   suggest modifying make_xml.py for wil to be more like
   make_xml.py for shs.
  shs is word-for-word the same as wil (examples guru, Gawa).
    Does shs extend WIL in any way?
  Needs revision to modern IAST spelling for proper names (e.g. all caps)
  without diacritics. Also Unadi.
* v00 generate  shs 07-24-2018

cd v00
python generate.py shs inventory.txt  makotemplates ../../SHSScan/2014/webv00

* install shs 
 python install.py shs ../../SHSScan/2014/webv00 ../../SHSScan/2014
EXTRA
cp -r ../../PWGScan/2013/web/fonts/ ../../SHSScan/2014/web/
cp ../../SHSScan/2014/pywork/shsheader.xml ../../SHSScan/2014/web/
#mv ../../SHSScan/2014/web_20180521/sqlite/shsbib.sqlite ../../SHSScan/2014/web/sqlite/shsbib.sqlite 
cd ../../SHSScan/2014/web/webtc2
sh init_query.sh
cd ../../../../websanlexicon/v00
* regenerate shs/web in place  
#in v00
python generate.py shs inventory.txt  makotemplates ../../SHSScan/2014/web

* ----------gst---------------------
* NOTES on GST conversion
  Several <lang n="greek"></lang> tags.
  <sup> elements made bold.
* v00 generate  gst 07-24-2018

cd v00
python generate.py gst inventory.txt  makotemplates ../../GSTScan/2014/webv00

* install gst 
 python install.py gst ../../GSTScan/2014/webv00 ../../GSTScan/2014
EXTRA
cp -r ../../PWGScan/2013/web/fonts/ ../../GSTScan/2014/web/
cp ../../GSTScan/2014/pywork/gstheader.xml ../../GSTScan/2014/web/
#mv ../../GSTScan/2014/web_20180521/sqlite/gstbib.sqlite ../../GSTScan/2014/web/sqlite/gstbib.sqlite 
cd ../../GSTScan/2014/web/webtc2
sh init_query.sh
cd ../../../../websanlexicon/v00
* regenerate gst/web in place  
#in v00
python generate.py gst inventory.txt  makotemplates ../../GSTScan/2014/web

* ----------vcp---------------------
* NOTES on VCP conversion
  In vcp.txt:  <P>, <HI>, <H>, <Picture> become <div n="P">" etc. in vcp.xml.
  Also, <> of vcp.txt becomes <lb/> in vcp.xml; 
    Perhaps push the xml codes down into vcp.txt?

* v00 generate  vcp 07-25-2018

cd v00
python generate.py vcp inventory.txt  makotemplates ../../VCPScan/2013/webv00

* install vcp 
 python install.py vcp ../../VCPScan/2013/webv00 ../../VCPScan/2013
EXTRA
cp -r ../../PWGScan/2013/web/fonts/ ../../VCPScan/2013/web/
cp ../../VCPScan/2013/pywork/vcpheader.xml ../../VCPScan/2013/web/
#mv ../../VCPScan/2013/web_20180521/sqlite/vcpbib.sqlite ../../VCPScan/2013/web/sqlite/vcpbib.sqlite 
cd ../../VCPScan/2013/web/webtc2
sh init_query.sh
cd ../../../../websanlexicon/v00
* regenerate vcp/web in place  
#in v00
python generate.py vcp inventory.txt  makotemplates ../../VCPScan/2013/web

* ----------ben---------------------
* NOTES on BEN conversion
  <g></g> tag for Greek (empty). Shld change to <lang n="greek"></lang>;
      this done in basicadjust.  (787 lines in ben.xml with <g></g>)
  <pic name="vatsa.png'/> requires vatsa.png in images folder;
  <P/> twice  (headword dIkz and garj):
      indented paragraph. Better to be <div n="P">. Coded this way in 
      basicadjust.
  -- changed to emdash in disp.php. 
  bold section headings -- could be converted to divs for better display.

 Improvement: Move [Pagexxx] at end of entry after <LEND>; this in ben.txt.
* v00 generate  ben 07-25-2018

cd v00
python generate.py ben inventory.txt  makotemplates ../../BENScan/2014/webv00

* install ben 
 python install.py ben ../../BENScan/2014/webv00 ../../BENScan/2014
EXTRA
cp -r ../../PWGScan/2013/web/fonts/ ../../BENScan/2014/web/
cp ../../BENScan/2014/pywork/benheader.xml ../../BENScan/2014/web/
cp ../../BENScan/2014/web_20160603/images/vatsa.png ../../BENScan/2014/web/images/
cd ../../BENScan/2014/web/webtc2
sh init_query.sh
cd ../../../../websanlexicon/v00
* regenerate ben/web in place  
#in v00
python generate.py ben inventory.txt  makotemplates ../../BENScan/2014/web

* ----------bop---------------------
* NOTES on BOP conversion
  

* v00 generate  bop 07-25-2018

cd v00
python generate.py bop inventory.txt  makotemplates ../../BOPScan/2014/webv00

* install bop 
 python install.py bop ../../BOPScan/2014/webv00 ../../BOPScan/2014
EXTRA
cp -r ../../PWGScan/2013/web/fonts/ ../../BOPScan/2014/web/
cp ../../BOPScan/2014/pywork/bopheader.xml ../../BOPScan/2014/web/
#mv ../../BOPScan/2014/web_20180521/sqlite/bopbib.sqlite ../../BOPScan/2014/web/sqlite/bopbib.sqlite 
cd ../../BOPScan/2014/web/webtc2
sh init_query.sh
cd ../../../../websanlexicon/v00
* regenerate bop/web in place  
#in v00
python generate.py bop inventory.txt  makotemplates ../../BOPScan/2014/web

* ----------bor---------------------
* NOTES on BOR conversion
  Part of the 'div' adjustment (that done in basicadjust) maybe should
   be done either in bor.xml or bor.txt.

* v00 generate  bor 07-25-2018

cd v00
python generate.py bor inventory.txt  makotemplates ../../BORScan/2014/webv00

* install bor 
 python install.py bor ../../BORScan/2014/webv00 ../../BORScan/2014
EXTRA
cp -r ../../PWGScan/2013/web/fonts/ ../../BORScan/2014/web/
cp ../../BORScan/2014/pywork/borheader.xml ../../BORScan/2014/web/
cd ../../BORScan/2014/web/webtc2
sh init_query.sh
cd ../../../../websanlexicon/v00
* regenerate bor/web in place  
#in v00
python generate.py bor inventory.txt  makotemplates ../../BORScan/2014/web

* ----------ccs---------------------
* NOTES on CCS conversion
  Part of the 'div' adjustment (that done in basicadjust) maybe should
   be done either in ccs.xml or ccs.txt.

* v00 generate  ccs 07-26-2018

cd v00
python generate.py ccs inventory.txt  makotemplates ../../CCSScan/2014/webv00

* install ccs 
 python install.py ccs ../../CCSScan/2014/webv00 ../../CCSScan/2014
EXTRA
#cp -r ../../pwg/web/fonts/ ../../CCSScan/2014/web/
cp ../../CCSScan/2014/pywork/ccsheader.xml ../../CCSScan/2014/web/
cd ../../CCSScan/2014/web/webtc2
sh init_query.sh
cd ../../../../websanlexicon/v00
* regenerate ccs/web in place  
#in v00
python generate.py ccs inventory.txt  makotemplates ../../CCSScan/2014/web

* ----------md---------------------
* NOTES on MD conversion
  

* v00 generate  md 07-26-2018

cd v00
python generate.py md inventory.txt  makotemplates ../../MDScan/2014/webv00

* install md 
 python install.py md ../../MDScan/2014/webv00 ../../MDScan/2014
EXTRA
cp -r ../../PWGScan/2013/web/fonts/ ../../MDScan/2014/web/
cp ../../MDScan/2014/pywork/mdheader.xml ../../MDScan/2014/web/
cd ../../MDScan/2014/web/webtc2
sh init_query.sh
cd ../../../../websanlexicon/v00
* regenerate md/web in place  
#in v00
python generate.py md inventory.txt  makotemplates ../../MDScan/2014/web

* ----------mwe---------------------
* NOTES on MWE conversion
* v00 generate  mwe 07-26-2018

cd v00
python generate.py mwe inventory.txt  makotemplates ../../MWEScan/2013/webv00

* install mwe 
 python install.py mwe ../../MWEScan/2013/webv00 ../../MWEScan/2013
EXTRA
cp -r ../../PWGScan/2013/web/fonts/ ../../MWEScan/2013/web/
cp ../../MWEScan/2013/pywork/mweheader.xml ../../MWEScan/2013/web/
cd ../../MWEScan/2013/web/webtc2
sh init_query.sh
cd ../../../../websanlexicon/v00
* regenerate mwe/web in place  
#in v00
python generate.py mwe inventory.txt  makotemplates ../../MWEScan/2013/web

* --------------------------------------------------------------
* redo_cologne_all.sh
This script runs generate.py for all the converted dictionaries,
  with parameters to update the active 'web' directory for each dictionary.
 in v00
 gra, bur, cae, stc, pwg, mw, skd, ae,
 pw,  ap, ap90, pd,  bhs, wil, yat, shs,
 gst, vcp, ben, bop, bor, ccs, md, mwe
* --------------------------------------------------------------
* apidev1
* --------------------------------------------------------------
* copy modules from webtc, and modify for apidev1.
** previous copies in apidev1
cp basicadjust.php.php temp_prev_basicadjust.php
cp basicadjust.php temp_prev_basicadjust.php
cp basicdisplay.php temp_prev_basicdisplay.php

** dalraw
cp v00/makotemplates/webtc/dal.php ../apidev1/dalraw.php
# also, change class name to Dalraw
** basicadjust
cp v00/makotemplates/webtc/basicadjust.php ../apidev1/basicadjust.php
additional changes: 
 a) dal.php -> dalraw.php (one)
 b) new Dal -> new Dalraw (three or more)
** basicdisplay ??
cp v00/makotemplates/webtc/disp.php ../apidev1/basicdisplay.php
# no additional changes

** modify apidev1/dalwhich.php
  for dictionaries that have been 'converted'.

* THE END
