python generate.py gra inventory.txt  makotemplates ../../gra/web
python generate.py bur inventory.txt  makotemplates ../../bur/web
python generate.py cae inventory.txt  makotemplates ../../cae/web
python generate.py stc inventory.txt  makotemplates ../../stc/web
python generate.py pwg inventory.txt  makotemplates ../../pwg/web
python generate.py mw inventory.txt  makotemplates ../../mw/web
python generate.py skd inventory.txt  makotemplates ../../skd/web
python generate.py ae inventory.txt  makotemplates ../../ae/web
python generate.py pw inventory.txt  makotemplates ../../pw/web
python generate.py ap90 inventory.txt  makotemplates ../../ap90/web
