python generate.py gra inventory.txt  makotemplates ../../gra/web
python generate.py bur inventory.txt  makotemplates ../../bur/web
python generate.py cae inventory.txt  makotemplates ../../cae/web
python generate.py stc inventory.txt  makotemplates ../../stc/web
python generate.py pwg inventory.txt  makotemplates ../../pwg/web
python generate.py mw inventory.txt  makotemplates ../../mw/web
python generate.py skd inventory.txt  makotemplates ../../skd/web
python generate.py ae inventory.txt  makotemplates ../../ae/web
python generate.py pw inventory.txt  makotemplates ../../pw/web
python generate.py ap90 inventory.txt  makotemplates ../../ap90/web
python generate.py ap inventory.txt  makotemplates ../../ap/web
python generate.py pd inventory.txt  makotemplates ../../pd/web
python generate.py bhs inventory.txt  makotemplates ../../bhs/web
python generate.py wil inventory.txt  makotemplates ../../wil/web
python generate.py yat inventory.txt  makotemplates ../../yat/web
python generate.py shs inventory.txt  makotemplates ../../shs/web
python generate.py gst inventory.txt  makotemplates ../../gst/web
