python generate.py gra inventory.txt  makotemplates ../../gra/web
python generate.py bur inventory.txt  makotemplates ../../bur/web
python generate.py cae inventory.txt  makotemplates ../../cae/web
python generate.py stc inventory.txt  makotemplates ../../stc/web
python generate.py pwg inventory.txt  makotemplates ../../pwg/web
python generate.py mw inventory.txt  makotemplates ../../mw/web
python generate.py skd inventory.txt  makotemplates ../../skd/web
python generate.py ae inventory.txt  makotemplates ../../ae/web
python generate.py pw inventory.txt  makotemplates ../../pw/web
python generate.py ap90 inventory.txt  makotemplates ../../ap90/web
python generate.py ap inventory.txt  makotemplates ../../ap/web
python generate.py pd inventory.txt  makotemplates ../../pd/web
python generate.py bhs inventory.txt  makotemplates ../../bhs/web
python generate.py wil inventory.txt  makotemplates ../../wil/web
python generate.py yat inventory.txt  makotemplates ../../yat/web
python generate.py shs inventory.txt  makotemplates ../../shs/web
python generate.py gst inventory.txt  makotemplates ../../gst/web
python generate.py vcp inventory.txt  makotemplates ../../vcp/web
python generate.py ben inventory.txt  makotemplates ../../ben/web
python generate.py bop inventory.txt  makotemplates ../../bop/web
python generate.py bor inventory.txt  makotemplates ../../bor/web
python generate.py ccs inventory.txt  makotemplates ../../ccs/web
python generate.py md inventory.txt  makotemplates ../../md/web
python generate.py mwe inventory.txt  makotemplates ../../mwe/web
python generate.py mw72 inventory.txt  makotemplates ../../mw72/web
python generate.py ieg inventory.txt  makotemplates ../../ieg/web
python generate.py inm inventory.txt  makotemplates ../../inm/web
python generate.py krm inventory.txt  makotemplates ../../krm/web
python generate.py mci inventory.txt  makotemplates ../../mci/web
#
python generate.py pe inventory.txt  makotemplates ../../pe/web
python generate.py pgn inventory.txt  makotemplates ../../pgn/web
python generate.py pui inventory.txt  makotemplates ../../pui/web
#
python generate.py sch inventory.txt  makotemplates ../../sch/web
python generate.py snp inventory.txt  makotemplates ../../snp/web
python generate.py vei inventory.txt  makotemplates ../../vei/web
python generate.py acc inventory.txt  makotemplates ../../acc/web
