python generate.py gra inventory.txt  makotemplates ../../GRAScan/2014/web
python generate.py bur inventory.txt  makotemplates ../../BURScan/2013/web
python generate.py cae inventory.txt  makotemplates ../../CAEScan/2014/web
python generate.py stc inventory.txt  makotemplates ../../STCScan/2013/web
python generate.py pwg inventory.txt  makotemplates ../../PWGScan/2013/web
python generate.py mw inventory.txt  makotemplates ../../MWScan/2014/web
python generate.py skd inventory.txt  makotemplates ../../SKDScan/2013/web
python generate.py ae inventory.txt  makotemplates ../../AEScan/2014/web
python generate.py pw inventory.txt  makotemplates ../../PWScan/2014/web
python generate.py ap90 inventory.txt  makotemplates ../../AP90Scan/2014/web
python generate.py ap inventory.txt  makotemplates ../../APScan/2014/web
python generate.py pd inventory.txt  makotemplates ../../PDScan/2014/web
python generate.py bhs inventory.txt  makotemplates ../../BHSScan/2014/web
python generate.py wil inventory.txt  makotemplates ../../WILScan/2014/web
python generate.py yat inventory.txt  makotemplates ../../YATScan/2014/web
python generate.py shs inventory.txt  makotemplates ../../SHSScan/2014/web
python generate.py gst inventory.txt  makotemplates ../../GSTScan/2014/web
