python generate.py gra inventory.txt  makotemplates ../../GRAScan/2014/web
python generate.py bur inventory.txt  makotemplates ../../BURScan/2013/web
python generate.py cae inventory.txt  makotemplates ../../CAEScan/2014/web
python generate.py stc inventory.txt  makotemplates ../../STCScan/2013/web
python generate.py pwg inventory.txt  makotemplates ../../PWGScan/2013/web
python generate.py mw inventory.txt  makotemplates ../../MWScan/2014/web
python generate.py skd inventory.txt  makotemplates ../../SKDScan/2013/web
python generate.py ae inventory.txt  makotemplates ../../AEScan/2014/web
python generate.py pw inventory.txt  makotemplates ../../PWScan/2014/web
python generate.py ap90 inventory.txt  makotemplates ../../AP90Scan/2014/web
python generate.py ap inventory.txt  makotemplates ../../APScan/2014/web
python generate.py pd inventory.txt  makotemplates ../../PDScan/2014/web
python generate.py bhs inventory.txt  makotemplates ../../BHSScan/2014/web
python generate.py wil inventory.txt  makotemplates ../../WILScan/2014/web
python generate.py yat inventory.txt  makotemplates ../../YATScan/2014/web
python generate.py shs inventory.txt  makotemplates ../../SHSScan/2014/web
python generate.py gst inventory.txt  makotemplates ../../GSTScan/2014/web
python generate.py vcp inventory.txt  makotemplates ../../VCPScan/2020/web
python generate.py ben inventory.txt  makotemplates ../../BENScan/2014/web
python generate.py bop inventory.txt  makotemplates ../../BOPScan/2014/web
python generate.py bor inventory.txt  makotemplates ../../BORScan/2014/web
python generate.py ccs inventory.txt  makotemplates ../../CCSScan/2014/web
python generate.py md inventory.txt  makotemplates ../../MDScan/2014/web
python generate.py mwe inventory.txt  makotemplates ../../MWEScan/2013/web
python generate.py mw72 inventory.txt  makotemplates ../../MW72Scan/2014/web
python generate.py ieg inventory.txt  makotemplates ../../IEGScan/2014/web
python generate.py inm inventory.txt  makotemplates ../../INMScan/2013/web
python generate.py krm inventory.txt  makotemplates ../../KRMScan/2014/web
python generate.py mci inventory.txt  makotemplates ../../MCIScan/2014/web
#
python generate.py pe inventory.txt  makotemplates ../../PEScan/2014/web
python generate.py pgn inventory.txt  makotemplates ../../PGNScan/2014/web
python generate.py pui inventory.txt  makotemplates ../../PUIScan/2014/web
#
python generate.py sch inventory.txt  makotemplates ../../SCHScan/2014/web
python generate.py snp inventory.txt  makotemplates ../../SNPScan/2014/web
python generate.py vei inventory.txt  makotemplates ../../VEIScan/2014/web
python generate.py acc inventory.txt  makotemplates ../../ACCScan/2014/web
